name: stickopy
description: This little piece of software, developed in Dart, allows you to copy the whole content of a USB drive automatically (when plugged), quickly and quietly.
version: 1.1.0
homepage: https://github.com/FLA-Coding/Stickopy

environment:
  sdk: '>=2.8.1 <3.0.0'