name: stickopy_silent
description: The silent version of Stickopy. You can copy any thumb drive connected to the PC, with nothing showing up at all.
version: 0.1.0
homepage: https://github.com/FLA-Coding/Stickopy

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  file_utils: '>=0.1.4'